FROM paperist/texlive-ja:latest
RUN apt update \
  && apt install -y \
  git\
  curl\
  unzip\
  libfontconfig1 \
  locales \
  && rm -rf /var/lib/apt/lists/*

# locale の設定
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
  && locale-gen

# bun のインストール
RUN curl -fsSL https://bun.sh/install | bash

# エイリアスの設定
RUN echo 'alias ga="git add"' >> ~/.bashrc
RUN echo 'alias gac="git commit -a -m"' >> ~/.bashrc
RUN echo 'alias gs="git status"' >> ~/.bashrc

# tex 用パッケージのインストール
RUN tlmgr update --self --all
RUN tlmgr install biber
RUN tlmgr install gb4e
RUN tlmgr install texcount
